### PR TITLE
Usability Feature Release

### PR DESCRIPTION
**Pull request by Harjot1Singh**
What's new:
- Persistent highlighting
- Keep track of page and line for each source (#14)
- Scroll highlighted line into center (#23)
- Scroll to top of next page (#30)
- Basic hotkeys (#20): ctrl+left, ctrl+right, left, right, tab, shift+tab, pageup, pagedown, ctrl+home, ctrl+end
- Hide empty sources from home (#34)
- Add page slider

c1923b85-2a6b-4af9-8130-ba0303e5d323

### CODE REVIEW

**Comment by Harjot1Singh** [comment]
`master` and `dev` are actually the same, but the commits references are different :/

**Comment by bhajneet** [comment]
Template doesn't include link to line (`/line/XYZ`) for 'View'.

image

**Comment by bhajneet** [comment]
The animation for scrolling to top of page after clicking "next page" is odd. It is loading the new page after scrolling up. It would be nicer to immediately delete/fade away the current page and insert the new page without any scroll change.

**Comment by bhajneet** [comment]
On mobile: Need to fix trackbar and it's indicator while scrolling. Doesn't show up as expected and once visible doesn't go away as expected.

**Pull request merged**
